# Generated by Django 3.1 on 2021-10-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrom', models.CharField(max_length=200)),
                ('pos', models.IntegerField()),
                ('ref', models.CharField(max_length=10)),
                ('alt', models.CharField(max_length=200)),
                ('filter', models.CharField(max_length=200)),
                ('af', models.FloatField()),
                ('vf', models.FloatField()),
                ('dp', models.IntegerField()),
                ('allele', models.CharField(max_length=200)),
                ('effect', models.CharField(max_length=200)),
                ('impact', models.CharField(max_length=200)),
                ('gene', models.CharField(max_length=200)),
            ],
        ),
    ]
